feat: send rules command
GolangUA/telegram-butler pull request #22
Opened 2024-03-26 19:21 UTC by hrvadl

Closes #21 
<img width="462" alt="image" src="https://github.com/GolangUA/telegram-butler/assets/93580374/1d46e3b3-fec6-4c01-95bb-ead2e9f7f42f">

2024-03-27 08:22 UTC, mymmrac requested changes

2024-03-27 08:22 UTC, mymmrac commented on internal/handler/message/handler.go
> +	bh.HandleMessageCtx(h.message)
Давай все-таки одразу через предикат будемо перевіряти команду `th.CommandEqual(rulesCmd)`

2024-03-27 08:22 UTC, mymmrac commented on internal/handler/message/handler.go
> +package message
Можливо цей пакет command назвати, будемо тут команди додавати, що думаєш?

2024-03-28 17:47 UTC, hrvadl commented on internal/handler/message/handler.go
> +	bh.HandleMessageCtx(h.message)
оу, я навіть не знав що він є
це було десь в доці ліби?

2024-03-28 17:48 UTC, hrvadl commented on internal/handler/message/handler.go
> +package message
@mymmrac дивлячись скільки у нас усього команд буде. Якщо багато - то має сенс дійсно перенести

2024-03-28 18:44 UTC, mymmrac approved these changes

2024-03-28 18:46 UTC, merged